### PR TITLE
Clean up readme, and add C++ workshop placeholder folder

### PR DESCRIPTION
**Pull request by rprakitpong**

### CODE REVIEW

**Comment by rprakitpong** [comment]
Renumbered the workshops to fit C++ workshop in

**Comment by rprakitpong** [comment]
Feel free to checkout into this branch and make your readme changes if you think I missed anything.

**Review by AndrewSiew — APPROVED** [review]
Everything seems good

**Review by MonicaNam — APPROVED** [review]
changes make sense, will keep the preworkshop/workshop balance in mind

**Pull request merged**
